%
% standalone optxagnf code input file
%
% optxagnf standalone v1.0.0
%
Jin et al AGN Library v2 Parameters: NLS, Astar = 0.0
param 1 BH Mass, 1e6-1e9, <= 9.0 as log10
1e9
param 2 Distance, < 1e6 as Mpc, > 1e6 as cm 413.5 in v1, 1.5e18 in v2
1.5d18
param 3 Luminosity, L/Ledd, log10 -6.0 - 0.0, >0 linear
1.00
param 4 Astar, - BH rotation parameter, usually 0.0
0.0d0
param 5 Rcor/Rg, inner edge of disk, >=6, 40 NLS 60 BLS, -ve disk only
40.0d0
param 6 Router/Rg, log10, usually 4.0-5.0, default 4.0
4.0d0
param 7 Compton Opt. Thick Temperature kTe in keV, ~0.2 NLS
0.2d0
param 8 Compton Opt. Thickness, ~0-20, 15 NLS
15.d0
param 9 Hard Component,-ve of powerlaw slope in Photons, 2.2/1.8 NSL/BLS
2.2d0
param 10 Fraction of corona power in hard component, 0.2/0.5 NLS/BLS
0.2d0
param 11 Redshift >=0.0, 0.1 in compSED v1 Library 0.0 in v2
0.0d0
